/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Frame.java to edit this template
 */
package Ejercicio2;

import java.text.DecimalFormat;

/**
 *
 * @author AlexanderCV
 */
public class FormDocente2 extends java.awt.Frame {

    /**
     * Creates new form FormDocente2
     */
    public FormDocente2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTxtNombre = new javax.swing.JTextField();
        jCboCategoria = new javax.swing.JComboBox<>();
        jCboEstudios = new javax.swing.JComboBox<>();
        JBtnMostrar = new javax.swing.JButton();
        jBtnLimpiar = new javax.swing.JButton();
        jSpnAñosServ = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLblCodigo = new javax.swing.JLabel();
        jLblNombre = new javax.swing.JLabel();
        jLblCategoria = new javax.swing.JLabel();
        jLblEstudios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaLista = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLblPagoParcial = new javax.swing.JLabel();
        jLblSueldoFinal = new javax.swing.JLabel();
        jLblDescuento = new javax.swing.JLabel();
        jLblBonificacion = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Docente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre y Apellidos"));
        jTxtNombre.setName(""); // NOI18N
        jPanel2.add(jTxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 180, -1));

        jCboCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --", "Principal", "Asociado", "Auxiliar" }));
        jCboCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        jCboCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboCategoriaActionPerformed(evt);
            }
        });
        jPanel2.add(jCboCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 50));

        jCboEstudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Seleccionar --", "Maestria", "Doctorado" }));
        jCboEstudios.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudios"));
        jCboEstudios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboEstudiosActionPerformed(evt);
            }
        });
        jPanel2.add(jCboEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 50));

        JBtnMostrar.setText("Mostrar");
        JBtnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnMostrarActionPerformed(evt);
            }
        });
        jPanel2.add(JBtnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 100, 30));

        jBtnLimpiar.setText("Limpiar");
        jBtnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(jBtnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 100, 30));

        jSpnAñosServ.setBorder(javax.swing.BorderFactory.createTitledBorder("Años de Servicio"));
        jPanel2.add(jSpnAñosServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 180, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 340));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Docente Registrado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblCodigo.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder("Codigo:"));
        jPanel3.add(jLblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 300, 40));

        jLblNombre.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblNombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres y Apellidos:"));
        jPanel3.add(jLblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 300, 40));

        jLblCategoria.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));
        jPanel3.add(jLblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 300, 40));

        jLblEstudios.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblEstudios.setBorder(javax.swing.BorderFactory.createTitledBorder("Estudios:"));
        jPanel3.add(jLblEstudios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 300, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 320, 190));

        jTxtAreaLista.setColumns(20);
        jTxtAreaLista.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jTxtAreaLista.setRows(5);
        jTxtAreaLista.setBorder(javax.swing.BorderFactory.createTitledBorder("Docentes Registrados"));
        jScrollPane1.setViewportView(jTxtAreaLista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 530, 150));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pagos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLblPagoParcial.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblPagoParcial.setBorder(javax.swing.BorderFactory.createTitledBorder("Pago Parcial"));
        jPanel4.add(jLblPagoParcial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 40));

        jLblSueldoFinal.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblSueldoFinal.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo Final"));
        jPanel4.add(jLblSueldoFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 180, 40));

        jLblDescuento.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblDescuento.setBorder(javax.swing.BorderFactory.createTitledBorder("Descuentos"));
        jPanel4.add(jLblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, 40));

        jLblBonificacion.setFont(new java.awt.Font("Segoe UI Light", 0, 12)); // NOI18N
        jLblBonificacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Bonificación"));
        jPanel4.add(jLblBonificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 180, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 210, 190));

        add(jPanel1, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void JBtnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnMostrarActionPerformed
        String nombres = jTxtNombre.getText();
        String categoria = jCboCategoria.getSelectedItem().toString();
        String estudios = jCboEstudios.getSelectedItem().toString();
        int horas = Integer.parseInt(jSpnAñosServ.getValue().toString());
        
        Docente profesor = new Docente();

        profesor.setNombre(nombres);
        profesor.setCategoria(categoria);
        profesor.setEstudios(estudios);
        profesor.setHoras(horas);
        String resumen = jTxtAreaLista.getText();

        jLblCodigo.setText(profesor.getCodigo());
        jLblNombre.setText(profesor.getNombre());
        jLblEstudios.setText(profesor.getEstudios());
        jLblCategoria.setText(profesor.getCategoria());
        
        jLblPagoParcial.setText("Pago Parcial : S/."+ redondeo(profesor.pagHora()));
        jLblBonificacion.setText("Bonificación : S/."+ redondeo(profesor.bonificacion()));
        jLblDescuento.setText("Descuento : S/." + redondeo(profesor.descuento()));
        jLblSueldoFinal.setText("Sueldo Final : S/." + redondeo(profesor.sueldoFinal()));
        jTxtAreaLista.setText(resumen + profesor.mostrarDatos());
        
        limpiar(0);
    }//GEN-LAST:event_JBtnMostrarActionPerformed

    private void jCboEstudiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboEstudiosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboEstudiosActionPerformed

    private void jCboCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboCategoriaActionPerformed
    
    private void jBtnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLimpiarActionPerformed
        limpiar(1);
    }//GEN-LAST:event_jBtnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void limpiar(int valor){
        if(valor==1){
            jLblCodigo.setText("");
            jLblNombre.setText("");
            jLblEstudios.setText("");
            jLblCategoria.setText("");

            jLblPagoParcial.setText("");
            jLblBonificacion.setText("");
            jLblDescuento.setText("");
            jLblSueldoFinal.setText("");
            jTxtAreaLista.setText("");

            jCboCategoria.setSelectedIndex(0);
            jCboEstudios.setSelectedIndex(0);
            jTxtNombre.setText("");
            jSpnAñosServ.setValue(0);

            jTxtNombre.requestFocus();
        }else{
            jCboCategoria.setSelectedIndex(0);
            jCboEstudios.setSelectedIndex(0);
            jTxtNombre.setText("");
            jSpnAñosServ.setValue(0);

            jTxtNombre.requestFocus();
        }
    }
    
    public String redondeo(double valor){
        DecimalFormat df = new DecimalFormat("#.##");
        return df.format(valor);
    }
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDocente2().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnMostrar;
    private javax.swing.JButton jBtnLimpiar;
    private javax.swing.JComboBox<String> jCboCategoria;
    private javax.swing.JComboBox<String> jCboEstudios;
    private javax.swing.JLabel jLblBonificacion;
    private javax.swing.JLabel jLblCategoria;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblDescuento;
    private javax.swing.JLabel jLblEstudios;
    private javax.swing.JLabel jLblNombre;
    private javax.swing.JLabel jLblPagoParcial;
    private javax.swing.JLabel jLblSueldoFinal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpnAñosServ;
    private javax.swing.JTextArea jTxtAreaLista;
    private javax.swing.JTextField jTxtNombre;
    // End of variables declaration//GEN-END:variables
}
